#!/usr/bin/env bash
# One-time setup: create environment, agent, and memory store; seed initial state.
# Re-run safe? No — agents/environments are created here. Subsequent edits use
# `ant beta:agents update`. This script is idempotent only via the early-exit
# checks below.
#
# Prereqs:
#   - ant CLI installed (https://github.com/anthropics/anthropic-cli)
#   - ANTHROPIC_API_KEY exported
#   - jq installed (for JSON parsing)
#
# Output: writes ai-tutor.env with AGENT_ID, ENV_ID, MEMORY_STORE_ID. Source
# this file from the runtime orchestrator.

set -euo pipefail

cd "$(dirname "$0")"

if [ -f ai-tutor.env ]; then
  echo "ai-tutor.env already exists — refusing to overwrite." >&2
  echo "Delete it manually if you want to re-create the agent + environment + memory store." >&2
  exit 1
fi

echo "==> Creating environment..."
ENV_ID=$(ant beta:environments create < ai-tutor.environment.yaml --transform id -r)
echo "    ENV_ID=$ENV_ID"

echo "==> Creating agent..."
AGENT_RESP=$(ant beta:agents create < ai-tutor.agent.yaml --format json)
AGENT_ID=$(echo "$AGENT_RESP" | jq -r .id)
AGENT_VERSION=$(echo "$AGENT_RESP" | jq -r .version)
echo "    AGENT_ID=$AGENT_ID"
echo "    AGENT_VERSION=$AGENT_VERSION"

echo "==> Creating memory store..."
MEMSTORE_ID=$(ant beta:memory-stores create \
  --name "ai-tutor" \
  --description "AI Tutor durable state: concepts.json, profile.md, run records, lessons learned." \
  --transform id -r)
echo "    MEMORY_STORE_ID=$MEMSTORE_ID"

echo "==> Seeding feeds.yaml..."
ant beta:memory-stores:memories create \
  --memory-store-id "$MEMSTORE_ID" \
  --path "/feeds.yaml" \
  --content "@./seed_feeds.yaml" > /dev/null
echo "    feeds.yaml seeded"

echo "==> Seeding concepts.json..."
ant beta:memory-stores:memories create \
  --memory-store-id "$MEMSTORE_ID" \
  --path "/concepts.json" \
  --content "@./seed_concepts.json" > /dev/null
echo "    concepts.json seeded"

echo "==> Writing ai-tutor.env..."
cat > ai-tutor.env <<EOF
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
AGENT_ID=$AGENT_ID
AGENT_VERSION=$AGENT_VERSION
ENV_ID=$ENV_ID
MEMORY_STORE_ID=$MEMSTORE_ID
EOF
chmod 600 ai-tutor.env

echo ""
echo "Done. Next steps:"
echo "  1. Fill in runtime/.env from runtime/.env.example."
echo "  2. Run runtime/orchestrator.py daily --kickoff 'ONBOARDING start' to send your essay request."
